project:
  type: website
  output-dir: docs
  resources:
    - _headers

website:
 # title: "BM"
  description: "um portfólio/blog/cantinho na internet"
 # favicon: icons8-home-32.png
  image: /assets/images/social-profile.png
  site-url: https://biamuniz.github.io
  repo-url: https://github.com/biamuniz.github.io
  open-graph: true
  twitter-card: true
  page-navigation: true
  page-footer:
    background: "DCD4CA"
    foreground: "black"
    #border: true
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2024 Bianca Muniz.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
  navbar:
    background: "transparent"
    foreground: "black"
    title: "[BM]{style='color: #853D5E; font-weight: bold; font-family: Bitter'}"
    search: true
    logo: assets/icons8-casa-50.png
    right:
      - text: "[Sobre]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
        href: sobre.qmd
      - text: "[Portfólio]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
        menu:
          - text: "[Programação]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
            href: programacao/index.qmd
          - text: "[Jornalismo]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
            href: jornalismo/index.qmd
          - text: "[Pesquisa]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
            href: http://lattes.cnpq.br/1196190520296373
      - text: "[Apresentações]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
        href: talks/index.qmd
      - text: "[Blog]{style='color: #853D5E; font-weight: bold; -webkit-text-stroke: 0.1px black;'}"
        href: blog.qmd

format:
  html:
    theme: assets/stylesheets/coeos.scss
   # css: styles.css
    lang: pt-br
    highlight-style: github-dark
    code-copy: true
    code-link: true
    anchor-sections: true
    link-external-newwindow: true
    fig-align: center
    code-tools:
      source: false
      toggle: false
      caption: none
    include-after-body:
      - text: |
          <script type="text/javascript">
          const dateElements = document.querySelectorAll("p.date, div.listing-date, div.listing-file-modified");
          dateElements.forEach((el) => {
            el.innerHTML = el.innerHTML.replace(
              /(\d+)(st|nd|rd|th)/g,
              "$1<sup style='font-size:0.5em;font-style:italic;'>$2</sup>"
            );
          });
          </script>


lightbox: auto

execute:
  freeze: true
