---
title: "Oi, eu sou a Bianca!"
page-layout: full
---

Sou uma pessoa. Uma mulher negra, filha da Cida e do Paulo. Mas também sou analista de dados na [Agência Pública](https://apublica.org/), jornalista formada pela Universidade de São Paulo, com período de intercâmbio em Empreendedorismo e Inovação realizado na Universidade do Texas em Austin, nos EUA. Tenho especialização em [Jornalismo de Dados, Automação e Data Storytelling](https://www.insper.edu.br/pos-graduacao/master-em-jornalismo-de-dados-automacao-e-data-storytelling/) pelo Insper. Antes disso, me formei em Biomedicina pela Universidade Federal de São Paulo e defendi um mestrado em Ciências pela mesma instituição.

Atualmente faço parteda [R-Ladies São Paulo](https://rladies-sp.org/), grupo que busca promover a diversidade de gênero na comunidade da linguagem programação R. Me interesso por tecnologia, dados, conhecimento aberto e suas relações com direitos humanos. E às vezes toco cordas com arco (já tentei violino e violoncelo, agora tô firme na viola erudita), brinco com fotografia analógica e faço uns desenhos.

## 

Você pode ver meu currículo mais detalhado abaixo:

{{< pdf assets/bianca-cv.pdf width=80% height=600 >}}
